apiVersion: v1  
kind: Pod
metadata:
  name: depod
  labels:
    app: depod
spec:
  containers:
  - image: hiage/depod:latest
    command:
      - "sleep"
      - "86400"
    imagePullPolicy: "Always"
    name: depod
  restartPolicy: Always